- name: setup cart
  hosts: cart
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating systemuser
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: removing app directory
    ansible.builtin.file:
      name: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: deleting cart application
    ansible.builtin.file:
      name: /tmp/cart.zip
      state: absent

  - name: downloading cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: extracting cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    community.general.npm:
      path: /app

  - name: setup systemd cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: reloading and starting cart
    ansible.builtin.systemd_service:
      name: cart
      state: started
      enabled: yes
      daemon_reload: true
