- name: setup user
  hosts: user 
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true
      shell: /sbin/nologion
      home: /app

  - name: remove app directory 
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: removing the user application file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: downloading user application to app directory
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unzipping file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  
  - name: installing dependencies
    community.general.npm:
      path: /app
      state: present

  - name: copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
      

  - name: start and reloading the server
    ansible.builtin.systemd_service:
      name: user
      daemon_reload: true
      enabled: yes
      state: started

